name: CreditsScore
description: A simple test for supporting tags {credit} for scorehud, credits are made by laithdev
author: ItzToxicGG
version: 1.0
main: credits\toxicgg\Main
api: 4.0.0
depend: [ScoreHud, Credits]
